print("i like food")
print("hello - Local")
print("cats are better then dogs")
print("sometimes i think about the dream of work without interuptions")
print("hello - Remote")
print("sometimes people dont do what i want")
print("sometimes i realize i just want to finish work")
print("Added durning merge")
print("remote end")

print("local end")
print("I forgor")
